name = "movie-recommendation-page"
main = ".open-next/worker.js"
compatibility_date = "2026-08-31"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "movie-recommender"
database_id = "d85e3455-f06c-4695-bf5d-3c4d260b41be"

[[routes]]
pattern = "movie.enescakmak.net"
custom_domain = true
